In [25]:
def replacechar(str1):
    char = str1[0]
    str1 = str1.replace(char,'$')
    str1 = char + str1[1:]
    return str1
print(replacechar('prospect'))

pros$ect


In [36]:
def swapchar(a,b):
    new_a=b[:2]+a[2]
    new_b=a[:2]+b[2]
    str1 = new_a + ', ' + new_b
    return str1
swapchar('abc', 'xyz')    

'xyc, abz'

In [51]:
def adding(str1):
    if len(str1)>2:
        if str1[-3:]=='ing':
            str1 = str1 + 'ly'
        else:
            str1 = str1 + 'ing'
    return str1
print(adding('ab'))
print(adding('abc'))
print(adding('string'))

ab
abcing
stringly


In [59]:
def findsubstring(str1):
    find_not = str1.find('not')
    find_poor = str1.find('poor')
    if find_poor>find_not and find_not>0 and find_poor>0:
        str1 = str1.replace(str1[find_not:(find_poor+4)],'good')
    return str1
print(findsubstring('The lyrics are not that poor!' 'The lyrics are poor!'))

The lyrics are good!The lyrics are poor!


In [65]:
def removeoddchars(str1):
    result = ""
    for i in range(len(str1)):
        if i % 2 == 0:
            result = result + str1[i]
    return result
removeoddchars('Navin')    

'Nvn'

In [77]:
def insert_end(str1):
    sub_str =""
    if len(str1)>1:
        sub_str = str1[-2:]
        return sub_str*4
    else:
        return str1
print(insert_end('Python'))
print(insert_end('Exercises'))
print(insert_end('n'))

onononon
eseseses
n


In [83]:
def first_three(str1):
    if len(str1)>2:
        sub_str = str1[0:3]
        return sub_str
    else:
        return str1
print(first_three('ipy'))
print(first_three('python'))
print(first_three('nav'))
print(first_three('na'))

ipy
pyt
nav
na


In [90]:
def print2decimals(a):
    print("\nOriginal Number:",a)
    print("Formatted Number upto 2 decimals:"+"{:.2f}".format(a))
print2decimals(3.1415926)
print2decimals(12.999)


Original Number: 3.1415926
Formatted Number upto 2 decimals:3.14

Original Number: 12.999
Formatted Number upto 2 decimals:13.00


In [1]:
def formatpercentage(num):
    print("Formatted Number in percentage:"+"{:.2%}".format(num))
formatpercentage(0.25)

Formatted Number in percentage:25.00%


In [4]:
def substringcount(substr, str1):
    return str1.count(substr)
substringcount('house','there is a fox in our house and neighbouring house')

2

In [8]:
def countchars(str1):
    print('o',str1.count('o'))
    print('e',str1.count('e'))
    print('u',str1.count('u'))
    print('h',str1.count('h'))
    print('r',str1.count('r'))
    print('t',str1.count('t'))
countchars('thequickbrownjumpsoverthelazydog')

o 3
e 3
u 2
h 2
r 2
t 2


In [26]:
import re
def countchars(str1):
    print('o',len(re.findall('o', str1)))
countchars('thequickbrownjumpsoverthelazydog')

o 3


In [20]:
def printSuperscript():
    print("The area of the rectangle is 1256.66cm\u00b2")
    print("The volume of the cylinder is 1254.725\u00b3")
printSuperscript()

The area of the rectangle is 1256.66cm²
The volume of the cylinder is 1254.725³


In [34]:
import string
alphabet = set(string.ascii_lowercase)
def ispanagram(str1):
    if set(str1) >= alphabet:
        return "Yes"
    else:
        return "No"
        
print(ispanagram("The quick brown fox jumps over the lazy dog"))
print(ispanagram("Naveen Kumar"))

Yes
No


In [9]:
def word_count(str1):
    counts = dict()
    words = str1.split()
    
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
    
    counts_x = sorted(counts.items(),key=lambda kv: kv[1])
    #print(counts_x)
    return counts_x[-2]

print(word_count("Heroes like Super man, Wonder Woman, Spider man, Bat man, Captain America, Iron Man are all super Heroes in cinemas only"))
    

('Heroes', 2)


In [16]:
import collections 
def min_window(str1, str2): 
    result_char, missing_char = collections.Counter(str2), len(str2) 
    i = p = q = 0 
    for j, c in enumerate(str1, 1): 
        missing_char -= result_char[c] > 0 
        result_char[c] -= 1 
        if not missing_char: 
            while i < q and result_char[str1[i]] < 0:
                result_char[str1[i]] += 1 
                i += 1 
            if not q or j - i <= q - p:
                p, q = i, j 
    return str1[p:q]

str1 = "PRWSOERIUSFK" 
str2 = "OSU"
print("Original Strings:\n",str1,"\n",str2)
print("Minimum window:") 
print(min_window(str1,str2))

Original Strings:
 PRWSOERIUSFK 
 OSU
Minimum window:
OERIUS


In [24]:
from collections import defaultdict
def find_sub_string(str): 
    str_len = len(str) 
      
    # Count all distinct characters. 
    dist_count_char = len(set([x for x in str])) 
  
    ctr, start_pos, start_pos_index, min_len = 0, 0, -1, 9999999999
    curr_count = defaultdict(lambda: 0) 
    for i in range(str_len): 
        curr_count[str[i]] += 1
 
        if curr_count[str[i]] == 1: 
            ctr += 1
  
        if ctr == dist_count_char: 
            while curr_count[str[start_pos]] > 1: 
                if curr_count[str[start_pos]] > 1: 
                    curr_count[str[start_pos]] -= 1
                start_pos += 1
  
            len_window = i - start_pos + 1
            if min_len > len_window: 
                min_len = len_window 
                start_pos_index = start_pos 
    return str[start_pos_index: start_pos_index + min_len]
str2 = "asdaewsqgtwwsa" 
print("Original Strings:\n",str2)
print("\nSmallest window that contains all characters of the said string:") 
print(find_sub_string(str2))

Original Strings:
 asdaewsqgtwwsa

Smallest window that contains all characters of the said string:
daewsqgt


In [29]:
def count_k_dist(str1, k):
    str_len = len(str1) 
    result = 0
    ctr = [0] * 27
    for i in range(0, str_len):
        dist_ctr = 0
        ctr = [0] * 27
        for j in range(i, str_len):
            if(ctr[ord(str1[j]) - 97] == 0):
                dist_ctr += 1
                ctr[ord(str1[j]) - 97] += 1
            if(dist_ctr == k):
                result += 1 
            if(dist_ctr > k):
                break
    return result
str1 = input("Input a string (lowercase alphabets):") 
k = int(input("Input k: "))
print("Number of substrings with exactly", k, "distinct characters : ", end = "") 
print(count_k_dist(str1, k))

Input a string (lowercase alphabets):wolf
Input k: 4
Number of substrings with exactly 4 distinct characters : 1


In [32]:
def num_of_substrings(str1):
    str1_len = len(str1)
    return int(str1_len * (str1_len+1) / 2)

str2 = input("Input a String:")
print("Number of substrings:")
print(num_of_substrings("w3resource"))

Input a String:w3resource
Number of substrings:
55


In [4]:
def no_of_substrings(str1):
    result = 0
    n = len(str1)
    for i in range(n):
        for j in range(i,n):
            if (str1[i]==str1[j]):
                result += 1
    return result
str1 = input("Input a String:")
print(no_of_substrings(str1))

Input a String:abcd
4


In [10]:
def count_no_of_strings(sample_list):
    ctr=0
    for each_str in sample_list:
        if len(each_str) > 1 and each_str[0] == each_str[-1]:
            ctr += 1
    return ctr
print(count_no_of_strings(['abc', 'xyz', 'wxw', '1331']))

2


In [15]:
def last(n):
    return n[-1]
def sort_list_last(tuples):
    return sorted(tuples,key=last)
print(sort_list_last([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


In [17]:
def remove_duplicates(sample):
    dup_items = set()
    uniq_items = []
    for x in sample:
        if x not in dup_items:
            uniq_items.append(x)
            dup_items.add(x)
    print(dup_items)
remove_duplicates([10,20,10,30,50,14,60,50,70])

{70, 10, 14, 50, 20, 60, 30}


In [30]:
def list_longer_than_n(sample,n):
    items = []
    words = sample.split(" ")
    for word in words:
        if len(word) > n:
            items.append(word)
    return items
print(list_longer_than_n('The quick brown fox jumps over the lazy dog',3))

['quick', 'brown', 'jumps', 'over', 'lazy']


In [33]:
def remove_element(sample):
    color = [x for (i,x) in enumerate(sample) if i not in (0,4,5)]
    return color
print(remove_element(['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']))

['Green', 'White', 'Black']


In [34]:
import itertools
print(list(itertools.permutations([12,2,3])))

[(12, 2, 3), (12, 3, 2), (2, 12, 3), (2, 3, 12), (3, 12, 2), (3, 2, 12)]


In [37]:
def convert_into_array(sample):
    return sorted(set().union(*sample))
convert_into_array([(1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10) ])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [21]:
class py_solution:
    def int_to_roman(self,num):
        val = [1000,900,500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1 ] 
        syb = [ "M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I" ]
        roman_num = ""
        i = 0
        while num >0:
            for _ in range(num//val[i]):
                roman_num += syb[i]
                num -= val[i]
            i += 1
        return roman_num

print(py_solution().int_to_roman(10))
print(py_solution().int_to_roman(3524))

X
MMMDXXIV


In [23]:
class py_solution:
    def roman_to_int(self,s):
        rom_val = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
        int_val = 0 
        for i in range(len(s)): 
            if i > 0 and rom_val[s[i]] > rom_val[s[i - 1]]: 
                int_val += rom_val[s[i]] - 2 * rom_val[s[i - 1]] 
            else: 
                int_val += rom_val[s[i]] 
        return int_val
print(py_solution().roman_to_int('MMMDXXIV'))

3524


In [24]:
class py_solution:
    def is_valid_parenthesis(self,str1):
        stack = []
        pchar = {'(': ')', '{': '}', '[': ']'}
        for parenthesis in str1:
            if parenthesis in pchar:
                stack.append(parenthesis)
            elif len(stack)==0 or pchar[stack.pop()]!= parenthesis:
                return False
        return len(stack)==0

print(py_solution().is_valid_parenthesis("(){}[]"))
print(py_solution().is_valid_parenthesis("()[{)}"))

True
False


In [10]:
class py_solution:
    def subsets(self,nums):
        output = [[]]
        for i in nums:
            output += [lst + [i] for lst in output]
        return output

fullList = [4, 5, 6]
p = py_solution()
print(p.subsets(fullList)) 

[[], [4], [5], [4, 5], [6], [4, 6], [5, 6], [4, 5, 6]]


In [20]:
class py_solution:
    def two_sum(self,nums,target):
        compliments={}
        result = []
        for index,num in enumerate(nums):
            if compliments.get(num) is None:
                compliments[target-num]=index
            else:
                result = compliments[num],index
        return result
    
input1=[10,20,10,40,50,60,70]
print(py_solution().two_sum(input1,30))

(0, 1)


In [2]:
class py_solution:
    def sum_zero(self,nums):
        nums.sort()
        result = []
        length = len(nums)
        for i in range(length-2):
            if i>0 and nums[i]==nums[i+1]:
                continue
            l = i+1
            r = length-1
            
            while l<r:
                total = nums[i]+nums[l]+nums[r]
                if total < 0:
                    l+=1
                elif total > 0:
                    r-=1
                else:
                    result.append([nums[i],nums[l],nums[r]])
                    while l<r and nums[l]==nums[l+1]:
                        l+=1
                    while l>r and nums[r]==nums[r+1]:
                        r-=1
                    l+=1
                    r-=1
        return result

num332=[-25, -10, -7, -3, 2, 4, 8, 10] 
print(py_solution().sum_zero(num332))               
        

[[-10, 2, 8], [-7, -3, 10]]


In [32]:
class py_solution:
    def threeSum(self, nums):
        nums, result, i = sorted(nums), [], 0
        while i < len(nums) - 2:
            j, k = i + 1, len(nums) - 1
            while j < k:
                if nums[i] + nums[j] + nums[k] < 0:
                    j += 1
                elif nums[i] + nums[j] + nums[k] > 0:
                    k -= 1
                else:
                    result.append([nums[i], nums[j], nums[k]])
                    j, k = j + 1, k - 1
                    while j < k and nums[j] == nums[j - 1]:
                        j += 1
                    while j < k and nums[k] == nums[k + 1]:
                        k -= 1
            i += 1
            while i < len(nums) - 2 and nums[i] == nums[i - 1]:
                i += 1
        return result

print(py_solution().threeSum([-25, -10, -7, -3, 2, 4, 8, 10]))

[[-10, 2, 8], [-7, -3, 10]]


In [5]:
class py_solution:
    def powe(self,x,n):
        return pow(x,n)
print(py_solution().powe(12,2))

144


In [17]:
class py_solution:
    def __init__(self):
        self.str1=""
    def get_String(self):
        self.str1 = input()
    def print_String(self):
        print(self.str1.upper())
str2=py_solution()
str2.get_String()
str2.print_String()

CoronaVirus
CORONAVIRUS


In [22]:
class Rectangle:
    def __init__(self,length,width):
        self.length,self.width = length,width
    def area(self):
        return self.length*self.width

rect = Rectangle(21,2)
print(rect.area())

42


In [25]:
class Circle:
    def __init__(self,radius):
        self.radius=radius
    def area(self):
        return self.radius**2*3.14
    def perimeter(self):
        return self.radius*2*3.14
circ =Circle(6)
print(circ.area())
print(circ.perimeter())

113.04
37.68


In [28]:
import itertools
x = itertools.cycle("ABCD")
print(type(x).__name__)

cycle


In [31]:
from collections import Counter
classes = ( ('V', 1), ('VI', 1), ('V', 2), ('VI', 2), ('VI', 3), ('VII', 1), )
students = Counter(class_name for class_name,no_students in classes)
print(students)    

Counter({'VI': 3, 'V': 2, 'VII': 1})


In [35]:
from collections import OrderedDict
dict = {'Angola':244,'Andorra':376, 'Algeria': 213, 'Afghanistan': 93, 'Albania': 355}
new_dict=OrderedDict(dict.items())
for key in new_dict:
    print(key,new_dict[key])
print("\nIn Reversed Order:")
for key in reversed(new_dict):
    print(key,new_dict[key])

Angola 244
Andorra 376
Algeria 213
Afghanistan 93
Albania 355

In Reversed Order:
Albania 355
Afghanistan 93
Algeria 213
Andorra 376
Angola 244


In [39]:
from collections import Counter
def compare_lists(list1,list2):
    return Counter(list1)==Counter(list2)
list1=[10,50,20,40,68,72,20,40]
list2=[50,40,72,68,10,20,40,20]
list3=[50,3,72,68,10,20,20,40]
print(compare_lists(list1,list2))
print(compare_lists(list1,list3))

True
False


In [45]:
from array import array
a = array("I",(1,2,5))
print(a.buffer_info())

(90632560, 3)


In [59]:
import array
a = array.array("i",[1,2,3,4,5,6])
print("Original array-")
print("A1:",a)

import binascii
bytes_array=a.tobytes()
print("Array of bytes:")
print(binascii.hexlify(bytes_array))

Original array-
A1: array('i', [1, 2, 3, 4, 5, 6])
Array of bytes:
b'010000000200000003000000040000000500000006000000'


In [74]:
import binascii
from array import array
array1 = array('i',[7,8,9,10])
print("array1 - ",array1)
as_bytes = array1.tobytes()
print("Bytes - ",binascii.hexlify(as_bytes))
array2 = array('i')
array2.frombytes(as_bytes)
print(array2)

array1 -  array('i', [7, 8, 9, 10])
Bytes -  b'0700000008000000090000000a000000'
array('i', [7, 8, 9, 10])


In [82]:
import heapq
heap=[]
heapq.heappush(heap,('VI', 1))
heapq.heappush(heap,('VII', 3))
heapq.heappush(heap,('VIII', 2))
print("Items in the heap-")
for a in heap:
    print(a)
print("The smallest item in the heap:",heap[0])
print("Pop the smallest item in the heap:")
heapq.heappop(heap)
for a in heap:
    print(a)

Items in the heap-
('VI', 1)
('VII', 3)
('VIII', 2)
The smallest item in the heap: ('VI', 1)
Pop the smallest item in the heap:
('VII', 3)
('VIII', 2)


In [88]:
import bisect
def index(a,x):
    return bisect.bisect_left(a,x)
a = [1,2,3,4]
print(index(a,10))
print(index(a,1))

4
0


In [91]:
import queue
q = queue.Queue()
for x in range(4):
    q.put(str(x))
while not q.empty():
    print(q.get(),end="")
print("\n")

0123



In [92]:
q

In [ ]:
q.get()

In [1]:
def harmonic_sum(n):
    if n < 2:
        return 1
    else:
        return 1 / n+harmonic_sum(n-1)
print(harmonic_sum(6))

2.4499999999999997


In [18]:
import numpy as np
x= np.ones((5,5))*6
print("Original Array - \n", x)
x[1:-1,1:-1]=0
print("\n 6 on the border and 0 inside in the array- \n", x)


Original Array - 
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]

 6 on the border and 0 inside in the array- 
 [[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


In [46]:
import numpy as np
x=np.ones((8,8), dtype=int)*3
x[1::2,::2]=9
x[::2,1::2]=9
x

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

In [54]:
import numpy as np
x=np.empty((3,3))
print(x)
y=np.full((3,5),6)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [65]:
import numpy as np
fvalues = [0, 12, 45.21 ,34, 99.91] 
F=np.array(fvalues)
print("Values in Fahrenheit degrees- \n",F)
print("Values in Centigrade degrees:")
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees- 
 [ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [72]:
import numpy as np
x=np.sqrt([1+0j])
y=np.sqrt([0+1j])
print(x)
print(y)
print("Real part")
print(np.real(x))
print("Imag part")
print(np.imag(x))

[1.+0.j]
[0.70710678+0.70710678j]
Real part
[1.]
Imag part
[0.]


In [75]:
import numpy as np
a1=np.array([0,10,20,40,60])
a2=np.array([0,40])
np.in1d(a1,a2)

array([ True, False, False,  True, False])

In [77]:
import numpy as np
a1=np.array([0,10,20,40,60])
a2=np.array([10,30,40])
np.intersect1d(a1,a2)

array([10, 40])

In [89]:
import numpy as np
a1=np.array([10,10,20,20,30,30])
a2=np.array(([1,1],[2,3]))
print(np.unique(a1))
print(np.unique(a2))

[10 20 30]
[1 2 3]


In [94]:
import numpy as np
a1=np.array([0,10,20,40,60,80])
a2=np.array([10, 30, 40, 50, 70])
print(np.setxor1d(a1,a2))

[ 0 20 30 50 60 70 80]


In [100]:
import numpy as np
print(np.all([[True,False],[True,False]]))
print(np.all([[True,True],[True,True]]))
print(np.all([1,2,30,0]))
print(np.all([10,20,-50]))

False
True
False
True


In [102]:
import numpy as np
print(np.any([[True,False],[True,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([1,2,30,0]))
print(np.any([10,20,-50]))
print(np.any(0))

True
True
True
True
False


In [109]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(np.tile(x,2))
print(np.tile(x,3))

[1 2 3 4]
[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


In [113]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(np.argmax(x))
print(np.argmin(x))

5
0


In [118]:
import numpy as np
a=np.array([1,2])
b=np.array([4,5])
print("a > b\n",np.greater(a,b))
print("a >= b\n",np.greater_equal(a,b))
print("a < b\n",np.less(a,b))
print("a <= b\n",np.less_equal(a,b))

a > b
 [False False]
a >= b
 [False False]
a < b
 [ True  True]
a <= b
 [ True  True]


In [124]:
import numpy as np
a=np.array([[4,6],[2,1]])
print("Sort along the first axis:")
print(np.sort(a,axis=0))
print("Sort along the last axis-")
print(np.sort(a,axis=1))

Sort along the first axis:
[[2 1]
 [4 6]]
Sort along the last axis-
[[4 6]
 [1 2]]


In [133]:
import numpy as np
first_names= ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery') 
last_names= ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum') 
x=np.lexsort((first_names,last_names))
print(x)

[0 1 2 3 4]


In [139]:
import numpy as np
a = np.array([[ 0,10,20],[20,30,40]])
print(a[a>10])
print(np.nonzero(a>10))

[20 20 30 40]
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [148]:
import numpy as np
a = np.zeros((4,4))
print(a.size*a.itemsize)

128


In [156]:
import numpy as np
print(np.zeros((1,2)))
print(np.zeros((1,2),dtype=np.int))
print(np.ones((1,2)))
print(np.ones((1,2),dtype=np.int))

[[0. 0.]]
[[0 0]]
[[1. 1.]]
[[1 1]]


In [171]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(x)
print("6 rows and 0 columns",x.shape)
x.shape=(3,2)
print("Reshaped array\n",x)

[1 2 3 4 5 6]
6 rows and 0 columns (6,)
Reshaped array
 [[1 2]
 [3 4]
 [5 6]]


In [175]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(x)
y=np.reshape(x,(3,2))
z=np.reshape(x,(2,3))
print("Reshape 3x2-\n",y)
print("Reshape 2x3-\n",z)

[1 2 3 4 5 6]
Reshape 3x2-
 [[1 2]
 [3 4]
 [5 6]]
Reshape 2x3-
 [[1 2 3]
 [4 5 6]]


In [181]:
import numpy as np
x=np.ones((3,5), dtype=np.uint)*2
y=np.full((3,5),fill_value=2,dtype=np.int)
print(x)
print(y)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [184]:
import numpy as np
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
