## Task 1 

Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def division():
    try :
        d = 5/0
    except:
        print("Error dividing by 0")

In [2]:
division()

Error dividing by 0


In [3]:
def division():
    try :
        d = 5/0
    except ZeroDivisionError:
        print("Error dividing by 0")

In [4]:
division()

Error dividing by 0


In [5]:
def division(n):
    try :
        d = 50/n
        return d
    except ZeroDivisionError:
        print("Error dividing by 0")

In [6]:
print(division(5))

10.0


In [7]:
division(0)

Error dividing by 0


## Task 1.2

In [8]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
    
sentence_list=[(sub + " " + verb + " " + obj + ".") for sub in subjects for verb in verbs for obj in objects]
for sentence in sentence_list:
    print (sentence)

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


## Task 2.1

In [9]:
import numpy as np
def vandermondeMatrix(inc):
    Output = np.vander(x,N, increasing=inc)
    return Output

x=[1,2,3,4,5,6]
N=5
print("When increasing argument is False:")
print(vandermondeMatrix(False))
print("When increasing argument is True:")
print(vandermondeMatrix(True))

When increasing argument is False:
[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]
When increasing argument is True:
[[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]]
